################################################################################
### Copyright (C) 2019 VMware, Inc.  All rights reserved.
### SPDX-License-Identifier: BSD-2-Clause
################################################################################
- name: get transport node uuid
  win_command: powershell.exe [xml]$cn = Get-Content {{InstallDir.value}}\controller-info.xml; $cn.config.transportNode.UUID
  register: tn_uuid
- name:
  fail: msg="invalid transport node uuid"
  when: tn_uuid.stdout == ""
