################################################################################
### Copyright (C) 2018 VMware, Inc.  All rights reserved.
### SPDX-License-Identifier: BSD-2-Clause
################################################################################
---
- hosts: servers_dhcp
  any_errors_fatal: true
  tasks:
    - name: config underlay mode
      set_fact:
        config_mode: 'config_mode=dhcp'
        underlay_mode: 'false'
    - import_tasks: system/get_os_type.yml
    - import_tasks: config/tn_uuid.yml
    - import_tasks: lsp/vif_id.yml
    - import_tasks: vif/int_br_name.yml
    - import_tasks: validation/vif_id_check.yml
    - import_tasks: config/app_intf_name.yml
    - import_tasks: lsp/create_lsp.yml
    - import_tasks: config/bms_config.yml
    - import_tasks: config/config.yml
    - import_tasks: vif/create_vif.yml
    - import_tasks: vif/attach_vif.yml
    - import_tasks: route/route.yml
    - name: create bm dir
      file:
        path: /opt/vmware/nsx-bm
        state: directory
        mode: 0755
    - name: create manual restore script
      copy:
        src: ./manual/static_dhcp_manual_restore.sh
        dest: /opt/vmware/nsx-bm/static_dhcp_manual_restore.sh
        owner: root
        group: root
        mode: 0755
    - name: create suse dhcp network configure file
      copy:
        src: templates/suse_dhcp_network_template.j2
        dest: /etc/sysconfig/network/ifcfg-{{ app_intf_name }}
        owner: root
        group: root
        mode: 0644
      when: os_type.stdout == "SUSE"
    - name: ifup application interface
      command: ifup {{ app_intf_name }}
      when: os_type.stdout == "SUSE"
    - name: config DHCP on App NIC
      command: dhclient -nw {{ app_intf_name }}
      when: os_type.stdout != "SUSE"
    - import_tasks: config/config.yml
    - name: create bootup script
      template:
        src: templates/bms_dhcp_init.j2
        dest: /etc/init.d/nsx-baremetal
        owner: root
        group: root
        mode: 0755
    - import_tasks: system/add_service_bootup.yml
